/** Notice * This file contains works from many authors under various (but compatible) licenses. Please see core.txt for more information. **/
(function(){(window.wpCoreControlsBundle=window.wpCoreControlsBundle||[]).push([[6],{359:function(ha,ca,h){function ba(f,h,n){h.endsWith("/")||(h+="/");n=n||{};var r=n.disableWebsockets||!1;this.lT=n.singleServerMode||!1;h.endsWith("blackbox/")||(h+="blackbox/");this.Gm=n.uploadData||null;this.Qv=n.uriData||null;this.hM=n.cacheKey||null;this.df=Object(e.a)(h,null,r);this.Lf=h;this.QD=f;this.kf=null;this.Nh=aa();this.Kl=aa();this.Xx=!1;this.Yf=this.Xd=this.qe=this.Ve=null;this.sf=[];this.Jy=[];this.cache={};this.timeStamp=
0;this.Hf=[];this.Qg=[];this.nE=null;this.JD=!1;this.CH=this.oh=this.id=null;this.eG=this.dP=fa;this.GA=0;this.mF=!1;this.e6=1;this.Pz={};this.hz=null;this.xr(!0)}function aa(){var e={promise:null,resolve:null,reject:null,state:0,result:null,request:null,lo:function(){return 1===(e.state&1)},c5:function(){return 2===(e.state&2)},Ih:function(){return!e.c5()&&!e.lo()},K4:function(){return 4===(e.state&4)},CS:function(){e.state|=4}};e.promise=new Promise(function(f,h){e.resolve=function(){if(0===e.state||
4===e.state)e.state=1,e.result=arguments[0],f.apply(null,arguments)};e.reject=function(){if(0===e.state||4===e.state)e.state=2,h.apply(null,arguments)}});return e}function fa(){return!1}function da(e,f,h){if(!(f in n))return!0;f=n[f];for(var r=0;r<f.length;r++){var w=e;var x=f[r];var y=h;if(x.name in w){var aa="",ba=!1;w=w[x.name];switch(x.type){case "s":aa="String";ba=Object(z.isString)(w);break;case "a":aa="Array";ba=Object(z.isArray)(w);break;case "n":aa="Number";ba=Object(z.isNumber)(w)&&Object(z.isFinite)(w);
break;case "o":aa="Object",ba=Object(z.isObject)(w)&&!Object(z.isArray)(w)}ba||y.reject('Expected response field "'+x.name+'" to have type '+aa);x=ba}else y.reject('Response missing field "'+x.name+'"'),x=!1;if(!x)return!1}return!0}h.r(ca);var z=h(0);h.n(z);var y=h(1);ha=h(35);var f=h(26),e=h(376),x=h(75),r=h(303),w=h(123),n={pages:[{name:"pages",type:"a"}],pdf:[{name:"url",type:"s"}],docmod:[{name:"url",type:"s"},{name:"rID",type:"s"}],health:[],tiles:[{name:"z",type:"n"},{name:"rID",type:"n"},{name:"tiles",
type:"a"},{name:"size",type:"n"}],annots:[{name:"url",type:"s"},{name:"name",type:"s"}],image:[{name:"url",type:"s"},{name:"name",type:"s"},{name:"p",type:"n"}],text:[{name:"url",type:"s"},{name:"name",type:"s"},{name:"p",type:"n"}]};ba.prototype=Object(z.extend)(ba.prototype,{o_:function(){var e=this;return new Promise(function(f,h){var n=new XMLHttpRequest;n.open("GET",e.Lf+"ck");n.withCredentials=e.Yn();n.onreadystatechange=function(){n.readyState===XMLHttpRequest.DONE&&(200===n.status?f():h())};
n.send()})},v$:function(e,f){this.dP=e||fa;this.eG=f||fa},xM:function(){var e=this;this.Kl=aa();this.Nh=aa();return this.df.bE().then(function(){e.Xx=!1;e.id=null;e.JD=!1;return e.o_()})},nH:function(){this.df.clientId=Object(f.j)(8);this.dP();this.vz();this.Ve&&(this.Ve.Ih()?this.lf(this.Ve.request):this.Ve.lo()&&this.eG(this.Ve.result.url,"pdf")&&(this.Ve=null,this.aS()));this.Yf&&this.Yf.Ih()&&this.lf(this.Yf.request);this.qe&&this.qe.Ih()?this.lf(this.qe.request):this.Xd&&this.Xd.Ih()&&this.RO(this.Xd.request);
var e;for(e=0;e<this.Hf.length;e++)this.Hf[e]&&this.Hf[e]&&(this.Hf[e].Ih()?this.lf(this.Hf[e].request):this.Hf[e].lo()&&this.eG(this.Hf[e].result.url,"image")&&(this.Hf[e]=null,this.DA(e)));for(e=0;e<this.Qg.length;e++)this.Qg[e]&&this.Qg[e]&&this.Qg[e].Ih()&&!this.Qg[e].K4()&&this.lf(this.Qg[e].request);for(e=0;e<this.sf.length;e++)this.sf[e]&&this.sf[e].Ih()&&this.lf(this.sf[e].request)},vz:function(e){var f=this;this.Xx||(this.timeStamp=Date.now(),this.df.jI(function(e){f.r6(e)},function(){return null},
function(){return null},this.df.clientId).then(function(){clearInterval(f.xA);f.xA=null},function(h){f.Xx=!1;if(!f.xA){var n=0;f.JD=!0;f.CH=0;f.xA=setInterval(function(){2>n++?f.nH():(clearInterval(f.xA),e&&e.reject(w.a),Object(y.e)("Blackbox connection failed:"+h))},5E3)}}),this.Xx=!0)},Gba:function(){var e=this,h=createPromiseCapability();if(this.Gm){var n=new FormData;n.append("file",this.Gm.fileHandle,this.Gm.fileHandle.name);var r=this.Gm.loadCallback;var w="upload";var x=this.Gm.extension}else if(this.Qv){n=
{uri:this.Qv.uri,qfa:this.Qv.shareId};n=Object.keys(n).map(function(e){return e+"="+(n[e]?encodeURIComponent(n[e]):"")}).join("&");var y="application/x-www-form-urlencoded; charset=UTF-8";r=this.Qv.loadCallback;w="url";x=this.Qv.extension}else return Promise.resolve();var z=new XMLHttpRequest;z.open("POST",Object(f.i)(e.Lf,"AuxUpload?ext="+x+"&type="+w+"&bcid="+this.df.clientId+"&auth="+this.oh));z.withCredentials=this.Yn();y&&z.setRequestHeader("Content-Type",y);z.addEventListener("load",function(){if(z.readyState===
z.DONE&&200===z.status){var f=JSON.parse(z.response);e.QD=f.uri;r(f);h.resolve(f)}});z.addEventListener("error",function(){h.reject(z.statusText+" "+JSON.stringify(z))});this.Gm&&null!=this.Gm.onProgress&&(z.upload.onprogress=function(f){e.Gm.onProgress(f)});z.send(n);return h.promise},M$:function(e){this.hz=e},J3:function(e){this.password&&this.Nh.lo()?e(this.password):this.hz(e)},h9:function(e){this.password=e||null;this.Nh.lo()||(this.vz(this.Nh),this.lf({t:"pages"}));return this.Nh.promise},jv:function(e){this.nE=
e||null;this.Nh.lo()||(this.vz(this.Nh),this.lf({t:"pages"}));return this.Nh.promise},zM:function(e){e=Object.assign(e,{uri:encodeURIComponent(this.QD)});this.nE&&(e.ext=this.nE);this.kf&&(e.c=this.kf);this.password&&(e.pswd=this.password);this.hM&&(e.cacheKey=this.hM);return e},lf:function(e){e=this.zM(e);this.df.send(e)},Wj:function(e){return e},r6:function(e){var f=this,h=e.data,n=e.err,r=e.t;if(n&&f.hz&&"This document could not be decrypted with the given password"===n)f.hz(function(e){f.h9(e)});
else switch(r){case "upload":n?f.Hba.reject(n):f.Hba.resolve("Success");break;case "pages":n?f.Nh.reject(n):da(h,r,f.Nh)&&f.Nh.resolve(h);break;case "config":n?f.Kl.reject(n):da(h,r,f.Kl)&&(h.id&&(f.id=h.id),h.auth&&(f.oh=h.auth),h.serverVersion&&(f.$ba=h.serverVersion,Object(y.f)("[WebViewer Server] server version: "+f.$ba)),h.serverID?(f.GA=h.serverID===f.CH&&f.mF?f.GA+1:0,f.CH=h.serverID):f.GA=0,f.mF=!1,f.Kl.resolve(h));break;case "health":n?f.Kl.reject(n):da(h,r,f.Kl)&&(h=h.unhealthy,f.lT&&h?
Object(y.h)("Server failed health check. Single server mode ignoring check."):!f.Oda&&h&&1>=f.GA&&(f.mF=!0,f.xM().then(function(){f.nH()},function(){f.nH()})));break;case "pdf":h.url=f.Lf+"../"+encodeURI(h.url)+"?bcid="+this.df.clientId+"&auth="+this.oh;n?f.Ve.reject(n):da(h,r,f.Ve)&&f.Ve.resolve(h);break;case "docmod":h.url=f.Lf+"../"+encodeURI(h.url)+"?bcid="+this.df.clientId+"&auth="+this.oh;n?f.Pz[h.rID].reject(n):da(h,r,f.Ve)&&f.Pz[h.rID].resolve(h);break;case "xod":if(n)this.qe&&this.qe.Ih()&&
this.qe.reject(n),this.Xd&&this.Xd.Ih()&&this.Xd.reject(n);else if(h.notFound)h.noCreate||this.qe&&this.qe.Ih()&&this.qe.resolve(h),this.Xd&&this.Xd.Ih()&&this.Xd.resolve(h);else{h.url&&(h.url=f.Lf+"../"+encodeURI(h.url)+"?bcid="+this.df.clientId+"&auth="+this.oh);if(!this.Xd||this.Xd.lo())this.Xd=aa(),this.Xd.request={t:"xod",noCreate:!0};this.qe||(this.qe=aa(),this.qe.request={t:"xod"});this.Xd.resolve(h);this.qe.resolve(h)}break;case "annots":if(n)f.Yf.reject(n);else if(da(h,r,f.Yf)){f.Yf.CS();
var w=new XMLHttpRequest;e=f.Lf+"../"+encodeURI(h.url);var z=h.hasAppearance?e+".xodapp?bcid="+this.df.clientId+"&auth="+this.oh:null;e+="?bcid="+this.df.clientId+"&auth="+this.oh;w.open("GET",e);w.responseType="text";w.withCredentials=this.Yn();w.addEventListener("load",function(){w.readyState===w.DONE&&200===w.status&&f.Yf.resolve({GI:w.response,UL:z})});w.addEventListener("error",function(){f.Yf.reject(w.statusText+" "+JSON.stringify(w))});w.send()}break;case "image":var ba=this.Hf[h.p];n?ba.promise.reject(n):
da(h,r,ba)&&(ba.result=h,ba.result.url=f.Lf+"../"+encodeURI(ba.result.url)+"?bcid="+this.df.clientId+"&auth="+this.oh,ba.resolve(ba.result));break;case "tiles":ba=h.rID;e=this.sf[ba];this.sf[ba]=null;this.Jy.push(ba);if(n)e.reject(n);else if(da(h,r,e)){for(n=0;n<h.tiles.length;n++)h.tiles[n]=f.Lf+"../"+encodeURI(h.tiles[n])+"?bcid="+this.df.clientId+"&auth="+this.oh;e.resolve(h)}break;case "text":ba=this.Qg[h.p];if(n)ba.reject(n);else if(da(h,r,ba)){ba.CS();var ca=new XMLHttpRequest;ca.open("GET",
f.Lf+"../"+encodeURI(h.url)+"?bcid="+this.df.clientId+"&auth="+this.oh);ca.withCredentials=this.Yn();ca.addEventListener("load",function(){ca.readyState===ca.DONE&&200===ca.status&&(ba.result=JSON.parse(ca.response),ba.resolve(ba.result))});ca.addEventListener("error",function(e){ba.reject(ca.statusText+" "+JSON.stringify(e))});ca.send()}break;case "progress":"loading"===h.t&&f.trigger(x.a.Events.DOCUMENT_LOADING_PROGRESS,[h.bytes,h.total])}},SN:function(){this.vz(this.Kl);return this.Kl.promise},
L1:function(){this.Yf||(this.Yf=aa(),this.Yf.request={t:"annots"},this.lf(this.Yf.request));return this.Yf.promise},DA:function(e){this.Hf[e]||(this.Hf[e]=aa(),this.Hf[e].request={t:"image",p:e},this.lf(this.Hf[e].request));return this.Hf[e].promise},i9:function(e){this.Qg[e]||(this.Qg[e]=aa(),this.Qg[e].request={t:"text",p:e},this.lf(this.Qg[e].request));return this.Qg[e].promise},j9:function(e,f,h,n){var r=this.sf.length;this.Jy.length&&(r=this.Jy.pop());this.sf[r]=aa();this.sf[r].request={t:"tiles",
p:e,z:f,r:h,size:n,rID:r};this.lf(this.sf[r].request);return this.sf[r].promise},aS:function(){this.Ve||(this.Ve=aa(),this.Ve.request={t:"pdf"},this.JD?this.Ve.resolve({url:this.QD}):this.lf(this.Ve.request));return this.Ve.promise},lO:function(e){var f=this,h=new XMLHttpRequest,n=this.Lf+"aul?id="+this.id+"&bcid="+this.df.clientId+"&auth="+this.oh,r=new FormData,w={};e.annots&&(w.annots="xfdf");e.watermark&&(w.watermark="png");e.redactions&&(w.redactions="redact");w={t:"docmod",reqID:this.e6++,parts:w};
e.print&&(w.print=!0);var x=this.zM(w);r.append("msg",JSON.stringify(x));return Promise.all([e.annots,e.watermark,e.redactions].map(function(e){return Promise.resolve(e)})).then(function(e){var w=e[0],y=e[1],z=e[2];w&&r.append("annots",w);y&&r.append("watermark",e.watermark);z&&r.append("redactions",z);f.Pz[x.reqID]=aa();h.open("POST",n);h.withCredentials=f.Yn;e=new Promise(function(e,f){h.onreadystatechange=function(){4===h.readyState&&(200===h.status?e():f("An error occurred while sending down annotation data to the server"))}});
h.send(r);return e.then(function(){return f.Pz[x.reqID].promise})})},RO:function(){this.Xd||(this.Xd=aa(),this.Xd.request={t:"xod",noCreate:!0},this.lf(this.Xd.request));return this.Xd.promise},k9:function(){this.qe||(this.qe=aa(),this.qe.request={t:"xod"},this.lf(this.qe.request));return this.qe.promise},qm:function(){return!0},request:function(){},vR:function(){},abort:function(){for(var e=0;e<this.sf.length;e++)this.sf[e]&&(this.sf[e].resolve(null),this.sf[e]=null,this.Jy.push(e));this.close()},
QA:function(e){this.kf=this.kf||{};this.kf.headers=e},jea:function(){return this.kf?Object(z.omit)(this.kf.headers,["Cookie","cookie"]):null},xr:function(e){this.kf=this.kf||{};this.kf.internal=this.kf.internal||{};this.kf.internal.withCredentials=e},Yn:function(){return this.kf&&this.kf.internal?this.kf.internal.withCredentials:null},getFileData:function(){return Promise.reject()}});Object(ha.b)(ba);Object(r.a)(ba);Object(r.b)(ba);ca["default"]=ba},376:function(ha,ca,h){function ba(h,z,y){function f(e,
f,h){function n(e){w().then(function(f){ca&&!da?setTimeout(function(){n(e)},1):f.send(JSON.stringify(e))})}function r(e,f,r,w){var ea=window.createPromiseCapability(),ia=!1,ja=ea;z=e;aa=f;ba=r;y=null;w&&(h=w);try{e=fa?ha+"/"+fa:ha+"/ws";e+="?bcid="+h;var ka=new WebSocket(e);ka.onopen=function(){ea.resolve();ia=!0;ea=null;ca=!1;x.resolve(ka);aa&&aa()};ka.onerror=function(e){ca=da=!0;ea&&ea.reject(e);y&&y.reject()};ka.onclose=function(){x=window.createPromiseCapability();ca=!0;y||(y=window.createPromiseCapability());
y.resolve();ba&&ba();z&&ia&&z({t:"health",data:{unhealthy:!0,isDead:!0}})};ka.onmessage=function(e){e&&e.data&&(e=JSON.parse(e.data),e.hb?n({hb:!0}):e.end?close():z(e))}}catch(Ea){ea.reject(Ea),ea=null}return ja.promise}function w(){ca&&z&&r(z);return x.promise}var x=window.createPromiseCapability(),y=null,z,aa,ba=null,ca=!1,da=!1,fa=f,ha=function(e){var f=e.indexOf("://"),h="ws://";0>f?f=0:(5===f&&(h="wss://"),f+=3);var n=e.lastIndexOf("/");0>n&&(n=e.length);return h+e.slice(f,n)}(e);return{send:n,
jI:r,bE:function(){return y?y.promise:w().then(function(e){y=window.createPromiseCapability();z=null;e.close();return y.promise})},clientId:h}}function e(e){var f=e.lastIndexOf("/");0>f&&(f=e.length);return e.slice(0,f)}var x=Object(fa.j)(8);return window.WebSocket&&!y?f(h,z,x):function(f,h,n){function r(e){(da?da.promise:Promise.resolve(ca)).then(function(f){var h=new XMLHttpRequest;f=ba?z+"/"+ba+"pf?id="+f:z+"/pf?id="+f;f+="&bcid="+n;var r=new FormData;r.append("data",JSON.stringify(e));h.open("POST",
f);h.withCredentials=!0;h.send(r)})}function w(){ca=0;da||(da=window.createPromiseCapability())}function x(){y=new XMLHttpRequest;var e=z+"/pf";e+=0!==ca?"?id="+ca+"&uc="+za:"?uc="+za;za++;y.open("GET",e,!0);y.withCredentials=!0;y.setRequestHeader("Cache-Control","no-cache");y.setRequestHeader("X-Requested-With","XMLHttpRequest");var f=y,h=!1;y.onreadystatechange=function(){a:if(3<=f.readyState&&!h){try{var e=f.responseText.length}catch(Ca){Object(aa.f)("caught exception");break a}if(0<e)try{var n=
f.responseText.split("\n");for(n[n.length-1]&&n.pop();0<n.length&&3>n[n.length-1].length;)"]"===n.pop()&&w();0<n.length&&3>n[0].length&&n.shift();for(e=0;e<n.length;++e)n[e].endsWith(",")&&(n[e]=n[e].substr(0,n[e].length-1));0===ca&&0<n.length&&(ca=JSON.parse(n.shift()).id,e=da,da=null,e.resolve(ca));var y;for(e=0;e<n.length;++e)(y=JSON.parse(n[e]))&&y.end?close():y&&y.hb&&y.id===ca?r({hb:!0}):Ba(y)}catch(Ca){}fa||(h=!0,x())}};y.send()}var y,z=e(f),ba=h,ca=0,da=window.createPromiseCapability(),fa=
!1,ha=null,Ba=null,za=0;return{send:r,jI:function(e,f,h){Ba=e;ha=h;fa=!1;w();x();f&&f();return Promise.resolve()},bE:function(){w();Ba=null;fa=!0;ha&&ha();y.abort();return Promise.resolve()},clientId:n}}(h,z,x)}h.d(ca,"a",function(){return ba});var aa=h(1),fa=h(26)}}]);}).call(this || window)
