/** Notice * This file contains works from many authors under various (but compatible) licenses. Please see core.txt for more information. **/
(function(){(window.wpCoreControlsBundle=window.wpCoreControlsBundle||[]).push([[7],{364:function(ha,ca,h){h.r(ca);var ba=h(3),aa=h(388),fa=h(389),da;(function(h){h[h.EXTERNAL_XFDF_NOT_REQUESTED=0]="EXTERNAL_XFDF_NOT_REQUESTED";h[h.EXTERNAL_XFDF_NOT_AVAILABLE=1]="EXTERNAL_XFDF_NOT_AVAILABLE";h[h.EXTERNAL_XFDF_AVAILABLE=2]="EXTERNAL_XFDF_AVAILABLE"})(da||(da={}));ha=function(){function h(h){this.N=h;this.state=da.EXTERNAL_XFDF_NOT_REQUESTED}h.prototype.F3=function(){var h=this;return function(f,e,x){return Object(ba.b)(h,
void 0,void 0,function(){var h,w,n,y,z,aa,ca,fa=this,ha;return Object(ba.d)(this,function(r){switch(r.label){case 0:if(this.state!==da.EXTERNAL_XFDF_NOT_REQUESTED)return[3,2];h=this.N.getDocument().qq();return[4,this.k2(h)];case 1:w=r.la(),n=this.LZ(w),this.iE=null!==(ha=null===n||void 0===n?void 0:n.parse())&&void 0!==ha?ha:null,this.state=null===this.iE?da.EXTERNAL_XFDF_NOT_AVAILABLE:da.EXTERNAL_XFDF_AVAILABLE,r.label=2;case 2:if(this.state===da.EXTERNAL_XFDF_NOT_AVAILABLE)return x(f),[2];y=new DOMParser;
z=y.parseFromString(f,"text/xml");e.forEach(function(e){fa.merge(z,fa.iE,e)});aa=new XMLSerializer;ca=aa.serializeToString(z);x(ca);return[2]}})})}};h.prototype.JH=function(h){this.k2=h};h.prototype.ce=function(){this.iE=void 0;this.state=da.EXTERNAL_XFDF_NOT_REQUESTED};h.prototype.LZ=function(h){return h?Array.isArray(h)?new aa.a(h):"string"!==typeof h?null:(new DOMParser).parseFromString(h,"text/xml").querySelector("xfdf > add")?new aa.a(h):new fa.a(h):null};h.prototype.merge=function(h,f,e){var x=
this;0===e&&(this.P5(h,f.un),this.R5(h,f.RD));var r=f.aa[e];r&&(this.S5(h,r.Cl),this.U5(h,r.kU,f.Ct),this.T5(h,r.page,e),this.Q5(h,r.UM));r=this.N.gc();if(e===r-1){var w=f.Ct;Object.keys(w).forEach(function(e){w[e].oF||x.fQ(h,e,w[e])})}};h.prototype.P5=function(h,f){null!==f&&(h=this.Os(h),this.Ko(h,"calculation-order",f))};h.prototype.R5=function(h,f){null!==f&&(h=this.Os(h),this.Ko(h,"document-actions",f))};h.prototype.S5=function(h,f){var e=this,x=this.Ns(h.querySelector("xfdf"),"annots");Object.keys(f).forEach(function(h){e.Ko(x,
'[name="'+h+'"]',f[h])})};h.prototype.U5=function(h,f,e){var x=this;if(0!==f.length){var r=this.Os(h);f.forEach(function(f){var n=f.getAttribute("field"),w=e[n];w&&(x.fQ(h,n,w),x.Ko(r,"null",f))})}};h.prototype.fQ=function(h,f,e){var x=this.Os(h);null!==e.Ey&&this.Ko(x,'ffield [name="'+f+'"]',e.Ey);h=this.Ns(h.querySelector("xfdf"),"fields");f=f.split(".");this.UG(h,f,0,e.value);e.oF=!0};h.prototype.T5=function(h,f,e){null!==f&&(h=this.Os(h),h=this.Ns(h,"pages"),this.Ko(h,'[number="'+(e+1)+'"]',f))};
h.prototype.Q5=function(h,f){Object.keys(f).forEach(function(e){(e=h.querySelector('annots [name="'+e+'"]'))&&e.parentElement.removeChild(e)})};h.prototype.UG=function(h,f,e,x){if(e===f.length)f=document.createElementNS("","value"),f.textContent=x,this.Ko(h,"value",f);else{var r=f[e];this.Ns(h,'[name="'+r+'"]',"field").setAttribute("name",r);h=h.querySelectorAll('[name="'+r+'"]');1===h.length?this.UG(h[0],f,e+1,x):(r=this.k1(h),this.UG(e===f.length-1?r:this.aba(h,r),f,e+1,x))}};h.prototype.k1=function(h){for(var f=
null,e=0;e<h.length;e++){var x=h[e];if(0===x.childElementCount||1===x.childElementCount&&"value"===x.children[0].tagName){f=x;break}}return f};h.prototype.aba=function(h,f){for(var e=0;e<h.length;e++)if(h[e]!==f)return h[e];return null};h.prototype.Ko=function(h,f,e){f=h.querySelector(f);null!==f&&h.removeChild(f);h.appendChild(e)};h.prototype.Os=function(h){var f=h.querySelector("pdf-info");if(null!==f)return f;f=this.Ns(h.querySelector("xfdf"),"pdf-info");f.setAttribute("xmlns","http://www.pdftron.com/pdfinfo");
f.setAttribute("version","2");f.setAttribute("import-version","3");return f};h.prototype.Ns=function(h,f,e){var x=h.querySelector(f);if(null!==x)return x;x=document.createElementNS("",e||f);h.appendChild(x);return x};return h}();ca["default"]=ha},374:function(ha,ca){ha=function(){function h(){}h.prototype.mx=function(h){var aa={un:null,RD:null,Ct:{},aa:{}};h=(new DOMParser).parseFromString(h,"text/xml");aa.un=h.querySelector("pdf-info calculation-order");aa.RD=h.querySelector("pdf-info document-actions");
aa.Ct=this.K6(h);aa.aa=this.W6(h);return aa};h.prototype.K6=function(h){var aa=h.querySelector("fields");h=h.querySelectorAll("pdf-info > ffield");if(null===aa&&null===h)return{};var ba={};this.PX(ba,aa);this.NX(ba,h);return ba};h.prototype.PX=function(h,aa){if(null!==aa&&aa.children){for(var ba=[],ca=0;ca<aa.children.length;ca++){var z=aa.children[ca];ba.push({name:z.getAttribute("name"),element:z})}for(;0!==ba.length;)for(aa=ba.shift(),ca=0;ca<aa.element.children.length;ca++)z=aa.element.children[ca],
"value"===z.tagName?h[aa.name]={value:z.textContent,Ey:null,oF:!1}:z.children&&ba.push({name:aa.name+"."+z.getAttribute("name"),element:z})}};h.prototype.NX=function(h,aa){aa.forEach(function(aa){var ba=aa.getAttribute("name");h[ba]?h[ba].Ey=aa:h[ba]={value:null,Ey:aa,oF:!1}})};h.prototype.W6=function(h){var aa=this,ba={};h.querySelectorAll("pdf-info widget").forEach(function(h){var z=parseInt(h.getAttribute("page"),10)-1;aa.xz(ba,z);ba[z].kU.push(h)});h.querySelectorAll("pdf-info page").forEach(function(h){var z=
parseInt(h.getAttribute("number"),10)-1;aa.xz(ba,z);ba[z].page=h});this.kO(h).forEach(function(h){var z=parseInt(h.getAttribute("page"),10),y=h.getAttribute("name");aa.xz(ba,z);ba[z].Cl[y]=h});this.VN(h).forEach(function(h){var z=parseInt(h.getAttribute("page"),10);h=h.textContent;aa.xz(ba,z);ba[z].UM[h]=!0});return ba};h.prototype.xz=function(h,aa){h[aa]||(h[aa]={Cl:{},UM:{},kU:[],page:null})};return h}();ca.a=ha},388:function(ha,ca,h){var ba=h(3),aa=h(0);h.n(aa);ha=function(h){function ca(z){var y=
h.call(this)||this;y.$0=Array.isArray(z)?z:[z];return y}Object(ba.c)(ca,h);ca.prototype.parse=function(){var h=this,y={un:null,RD:null,Ct:{},aa:{}};this.$0.forEach(function(f){y=Object(aa.merge)(y,h.mx(f))});return y};ca.prototype.kO=function(h){var y=[];h.querySelectorAll("add > *").forEach(function(f){y.push(f)});h.querySelectorAll("modify > *").forEach(function(f){y.push(f)});return y};ca.prototype.VN=function(h){return h.querySelectorAll("delete > *")};return ca}(h(374).a);ca.a=ha},389:function(ha,
ca,h){var ba=h(3);ha=function(h){function aa(aa){var z=h.call(this)||this;z.a1=aa;return z}Object(ba.c)(aa,h);aa.prototype.parse=function(){return this.mx(this.a1)};aa.prototype.kO=function(h){return h.querySelectorAll("annots > *")};aa.prototype.VN=function(){return[]};return aa}(h(374).a);ca.a=ha}}]);}).call(this || window)
