/** Notice * This file contains works from many authors under various (but compatible) licenses. Please see core.txt for more information. **/
(function(){(window.wpCoreControlsBundle=window.wpCoreControlsBundle||[]).push([[0],{349:function(ha,ca,h){h.r(ca);h.d(ca,"ByteRangeRequest",function(){return la});var ba=h(3),aa=h(0);h.n(aa);var fa=h(1),da=h(119);ha=h(75);var z=h(202),y=h(54),f=h(50),e=h(201),x=h(135);h=h(303);var r=[],w=[],n=window,ea=function(){return function(){this.Mk=1}}(),ia;(function(e){e[e.UNSENT=0]="UNSENT";e[e.DONE=4]="DONE"})(ia||(ia={}));var la=function(){function f(f,h,r,w){var x=this;this.url=f;this.range=h;this.Af=r;this.withCredentials=
w;this.$V=ia;this.request=new XMLHttpRequest;this.request.open("GET",this.url,!0);n.Uint8Array&&(this.request.responseType="arraybuffer");w&&(this.request.withCredentials=w);na.DISABLE_RANGE_HEADER||(Object(aa.isUndefined)(h.stop)?this.request.setRequestHeader("Range","bytes="+h.start):this.request.setRequestHeader("Range",["bytes=",h.start,"-",h.stop-1].join("")));this.request.setRequestHeader("X-Requested-With","XMLHttpRequest");r&&Object.keys(r).forEach(function(e){x.request.setRequestHeader(e,
r[e])});this.request.overrideMimeType?this.request.overrideMimeType("text/plain; charset=x-user-defined"):this.request.setRequestHeader("Accept-Charset","x-user-defined");this.status=e.a.NOT_STARTED}f.prototype.start=function(f){var h=this,r=this.request;r.onreadystatechange=function(){if(h.aborted)return h.status=e.a.ABORTED,f({code:e.a.ABORTED});if(this.readyState===h.$V.DONE){h.az();var w=0===window.document.URL.indexOf("file:///");200===r.status||206===r.status||w&&0===r.status?(w=n.uO(this),
h.Gr(w,f)):(h.status=e.a.ERROR,f({code:h.status,status:h.status}))}};this.request.send(null);this.status=e.a.STARTED};f.prototype.Gr=function(f,h){this.status=e.a.SUCCESS;if(h)return h(!1,f)};f.prototype.abort=function(){this.az();this.aborted=!0;this.request.abort()};f.prototype.az=function(){var e=Object(x.b)(this.url,this.range,w);-1!==e&&w.splice(e,1);if(0<r.length){e=r.shift();var h=new f(e.url,e.range,this.Af,this.withCredentials);e.request=h;w.push(e);h.start(Object(x.c)(e))}};f.prototype.extend=
function(e){var f=Object.assign({},this,e.prototype);f.constructor=e;return f};return f}(),na=function(e){function h(f,h,n,r,w){n=e.call(this,f,n,r)||this;n.Ok={};n.Jx=h;n.url=f;n.DISABLE_RANGE_HEADER=!1;n.bv=la;n.ZI=3;n.Af=w||{};return n}Object(ba.c)(h,e);h.prototype.dt=function(e,h,n){var r=-1===e.indexOf("?")?"?":"&";switch(n){case !1:case f.a.NEVER_CACHE:e=e+r+"_="+Object(aa.uniqueId)();break;case !0:case f.a.CACHE:e=e+r+"_="+h.start+","+(Object(aa.isUndefined)(h.stop)?"":h.stop)}return e};h.prototype.JM=
function(e,f,h,n){void 0===h&&(h={});return new this.bv(e,f,h,n)};h.prototype.S0=function(e,f,h,n,x){for(var y=0;y<r.length;y++)if(Object(aa.isEqual)(r[y].range,f)&&Object(aa.isEqual)(r[y].url,e))return r[y].ag.push(n),r[y].Xz++,null;for(y=0;y<w.length;y++)if(Object(aa.isEqual)(w[y].range,f)&&Object(aa.isEqual)(w[y].url,e))return w[y].ag.push(n),w[y].Xz++,null;h={url:e,range:f,Jx:h,ag:[n],Xz:1};if(0===r.length&&w.length<this.ZI)return w.push(h),h.request=this.JM(e,f,x,this.withCredentials),h;r.push(h);
return null};h.prototype.gm=function(e,f,h){var n=this.dt(e,f,this.Jx);(e=this.S0(n,f,this.Jx,h,this.Af))&&e.request.start(Object(x.c)(e));return function(){var e=Object(x.b)(n,f,w);if(-1!==e){var h=--w[e].Xz;0===h&&w[e].request&&w[e].request.abort()}else e=Object(x.b)(n,f,r),-1!==e&&(h=--r[e].Xz,0===h&&r.splice(e,1))}};h.prototype.ZN=function(){return{start:-da.a}};h.prototype.Q3=function(){var e=-(da.a+da.e);return{start:e-da.d,end:e}};h.prototype.Tq=function(e){var f=this;this.Ox=!0;var h=da.a;
this.gm(this.url,this.ZN(),function(n,r,w){function x(){var h=f.Gd.WN();f.gm(f.url,h,function(n,r){if(n)return Object(fa.h)("Error loading central directory: "+n),e(n);r=Object(y.a)(r);if(r.length!==h.stop-h.start)return e("Invalid XOD file: Zip central directory data is wrong size! Should be "+(h.stop-h.start)+" but is "+r.length);f.Gd.mR(r);f.rD=!0;f.Ox=!1;return e(!1)})}if(n)return Object(fa.h)("Error loading end header: "+n),e(n,r,w);r=Object(y.a)(r);if(r.length!==h)return e("Invalid XOD file: Zip end header data is wrong size!");
try{f.Gd=new z.a(r)}catch(pa){return e(pa)}f.Gd.m5?f.gm(f.url,f.Q3(),function(h,n){if(h)return Object(fa.h)("Error loading zip64 header: "+h),e(h);n=Object(y.a)(n);f.Gd.D5(n);x()}):x()})};h.prototype.rO=function(e){e(Object.keys(this.Gd.Ol))};h.prototype.XG=function(e,f){var h=this;if(this.Gd.BM(e)){var n=this.Gd.Uy(e);if(n in this.Ok){var r=this.Wg[e];r.Qp=this.Ok[n];r.Qp.Mk++;r.cancel=r.Qp.cancel}else{var w=this.Gd.l2(e),x=this.gm(this.url,w,function(r,x){r?(Object(fa.h)('Error loading part "'+
e+'": '+r),h.gm(h.url,w,function(r,x){if(r)return f(r,e);h.qR(x,w,n,e,f)})):h.qR(x,w,n,e,f)}),y=this.Wg[e];y&&(y.uT=!0,y.cancel=function(){y.Qp.Mk--;0===y.Qp.Mk&&(x(),delete h.Ok[n])},this.Ok[n]=new ea(n),y.Qp=this.Ok[n],y.Qp.cancel=y.cancel)}}else delete this.Wg[e],f(Error('File not found: "'+e+'"'),e)};h.prototype.qR=function(e,f,h,n,r){if(e.length!==f.stop-f.start)r(Error("Part data is wrong size!"),n);else{do{if(!this.Ok[h])return;n=this.Ok[h].Mk;for(var w=f.Lo.length,x=0;x<w;++x){var y=f.Lo[x];
r(!1,y.Go,e["string"===typeof e?"substring":"subarray"](y.start,y.stop),this.Gd.tP(y.Go));y.Go in this.Wg&&delete this.Wg[y.Go]}}while(n!==this.Ok[h].Mk);delete this.Ok[h]}};h.DISABLE_RANGE_HEADER=!1;h.ZI=3;return h}(ha.a);(function(e){function f(f,h,n){var r=e.call(this)||this,w;for(w in f)r[w]=f[w];r.Uea=f;r.startOffset=h;r.endOffset=n;r.JM=function(e,h,n,w){Object(aa.isUndefined)(h.stop)?(h.start+=r.endOffset,h.stop=r.endOffset):(h.start+=r.startOffset,h.stop+=r.startOffset);e=r.dt(r.url,h,r.Jx);
return new f.bv(e,h,n,w)};return r}Object(ba.c)(f,e);return f})(na);Object(h.a)(na);Object(h.b)(na);ca["default"]=na}}]);}).call(this || window)
